# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my_first_nbdev_project',
                'doc_host': 'https://Manjunath-Yelipeta.github.io',
                'git_url': 'https://github.com/Manjunath-Yelipeta/my_first_nbdev_project',
                'lib_path': 'my_first_nbdev_project'},
  'syms': {'my_first_nbdev_project.core': {'my_first_nbdev_project.core.foo': ('core.html#foo', 'my_first_nbdev_project/core.py')}}}
